[env:rpipico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
board_build.core = earlephilhower

board_build.arduino.earlephilhower.usb_manufacturer = Raspberry Pi
board_build.arduino.earlephilhower.usb_product = Pico W

build_flags =
	-DDEFAULT_FTP_SERVER_NETWORK_TYPE_RP2040=NETWORK_RP2040_WIFI
	-DDEFAULT_STORAGE_TYPE_RP2040=STORAGE_SD
	-DUSBCON
    -D ENABLE_DEBUG_LOG

extra_scripts = pre:scripts/generate_pio_headers.py
lib_deps =
	adafruit/Adafruit GFX Library @ ^1.11.11
	adafruit/Adafruit SSD1306 @ ^2.5.13